name: Attendace
description: Company Attendance


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.3.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.4.3+1
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  awesome_dialog: ^3.2.1
  url_launcher: ^6.3.0
  device_information: ^0.0.4
  dartz: ^0.10.1
  get_it: ^7.7.0
  rename: ^3.0.2 
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.3.1
  buttons_tabbar: ^1.3.10 
  flutter_lints: ^4.0.0 
  file_picker: ^8.0.5
  otp_text_field: ^1.1.3
  image_picker: ^1.1.2 
  path_provider: ^2.1.3 
  open_file: ^3.3.2
  device_preview: ^1.2.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/

  fonts:
    - family: VisbyCF
      fonts:
        - asset: assets/fonts/VisbyCF-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/VisbyCF-Bold.otf
          weight: 700
        - asset: assets/fonts/VisbyCF-Medium.otf
          weight: 600
        - asset: assets/fonts/VisbyCF-Regular.otf
          weight: 500
        - asset: assets/fonts/VisbyCF-Heavy.otf
          weight: 900
       
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

