name: Attendace
description: Company Attendance


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  awesome_dialog: ^3.2.0
  url_launcher: ^6.2.5
  device_information: ^0.0.4
  dartz: ^0.10.1
  get_it: ^7.6.7
  rename: ^3.0.1
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.3.1
  buttons_tabbar: ^1.3.8
  flutter_lints: ^3.0.1
  file_picker: ^6.1.1
  otp_text_field: ^1.1.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  video_player: ^2.8.2

dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/

  fonts:
    - family: Visby
      fonts:
        - asset: assets/fonts/VisbyLight.otf
          weight: 300
        - asset: assets/fonts/VisbyBold.otf
          weight: 700
        - asset: assets/fonts/VisbyMedium.otf
          weight: 500
        - asset: assets/fonts/VisbyRegular.otf
          weight: 400
        - asset: assets/fonts/VisbySemibold.otf
          weight: 600
       
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

